### ISSUE TITLE
Postgresql driver is not loaded with Gradle dependences

### ISSUE THREAD

**Issue by marl0rd** [marlontrujillo1080/eru#15]
After build the project, if you run it the following exception shows up:

`javax.persistence.PersistenceException: [PersistenceUnit: com.psv.jpa] Unable to build EntityManagerFactory`

`Caused by: org.hibernate.service.classloading.spi.ClassLoadingException: Specified JDBC Driver org.postgresql.Driver class not found`

`Caused by: org.hibernate.service.classloading.spi.ClassLoadingException: Unable to load class [org.postgresql.Driver]`

**Comment by gilbertojrequena** [comment]
I think I forgot to add the Postgres dependency
