### ISSUE TITLE
Scene Builder embedding :fire: :fire: :fire:

### ISSUE THREAD

**Issue by marl0rd** [marlontrujillo1080/eru#16]
**This is a big topic.**
For now, we create:
- Connections. The way to connect to external devices.
- Devices: The object to manage the data from external devices.
- Tags: Selected data from devices to manipulate it and put it in a real context.

The next mileston is create the displays, so the user can create Human Machine Interfaces using the Dynamo library gauges that are already working. 

**Simple scope**:
Just one display in fine (no links to other displays).

**Proposal**
Create another main tree item in the project tree called Displays and when someone double click it the App shows the embedded Scene Builder in the mainPane of the Skeleton. Sounds easy...

**Steps**

- [x] Create the Display class and add it to the TreeItem.
- [x] Add the behavior to open Scene Builder when the Display Tree Item is double click it.
- [x] Embed Scene Builder in eru.
- [x] Modify the Scene Builder to show the Dynamo gauges. This is kind simple because there is a way already in Scene Builder to add jar files that contains gauges and when the Dynamo Module is jared you can add it without problem.
- [ ] ~~Link gauges to tags.~~
- [x] Test test and test.

Good luck

**Comment by marl0rd** [comment]
SceneBuilder is an open source project.
Binaries for SceneBuilder are now available through Gluon. SceneBuilder was split into two parts:

SceneBuilderKit (a reusable framework)
SceneBuilder (the actual SceneBuilder application, built using the framework).
SceneBuilder source is currently still hosted as part of the JavaFX source repository (which is also open source). The current development version of SceneBuilder based upon Java 9 development efforts is located at:

http://hg.openjdk.java.net/openjfx/9-dev/rt/file/tip/apps/scenebuilder
Work was done on the SceneBuilder application itself so that it is able to be embedded into an IDE directly rather than needing to run as a stand-alone application (though it can also still run as a stand-alone application).

**Comment by marl0rd** [comment]
Here the repository:
https://bitbucket.org/gluon-oss/scenebuilder

**Comment by marl0rd** [comment]
@gilbertojrequena There is something interesting. In My InteliiJ installation there is a jar file in : 

> /opt/idea/idea-IU-171.4249.39/plugins/javaFX/lib

Seems like IntelliJ use it to embed Scene Builder... Keep searching...

**Comment by gilbertojrequena** [comment]
Yes, I just addressed how IntelliJ uses it, I'm still digging into it :)

**Comment by marl0rd** [comment]
If you look inside the jar, it uses only the kit (as my second comment said). And IJ is not using the GLUON version, is using the oracle instead.

/opt/idea/idea-IU-171.4249.39/plugins/javaFX/lib/SceneBuilderKit-8.2.0.jar:

/com/oracle/javafx/scenebuilder/kit/

**Comment by gilbertojrequena** [comment]
Actually they are using GLUON. As per https://github.com/JetBrains/intellij-community/blob/0be5219fa7f32612d6dec71845a12599d4940b15/platform/build-scripts/groovy/org/jetbrains/intellij/build/CommunityLibraryLicenses.groovy#L332

**Comment by marl0rd** [comment]
I am looking how the Scene Builder is open by itself using the kit here:
[https://bitbucket.org/gluon-oss/scenebuilder/src/6727faef1349b6ad603fe20a772b83d29d3c8c83/src/main/java/com/oracle/javafx/scenebuilder/app/SceneBuilderApp.java?at=default&fileviewer=file-view-default](https://bitbucket.org/gluon-oss/scenebuilder/src/6727faef1349b6ad603fe20a772b83d29d3c8c83/src/main/java/com/oracle/javafx/scenebuilder/app/SceneBuilderApp.java?at=default&fileviewer=file-view-default)

**Comment by marl0rd** [comment]
Bassically:
```
public void performControlAction(ApplicationControlAction a, DocumentWindowController source) {
        switch (a) {
...
            case NEW_FILE:
                final DocumentWindowController newWindow = makeNewWindow();
                newWindow.loadWithDefaultContent();
                newWindow.openWindow();
                break;
...
            case OPEN_FILE:
                performOpenFile(source);
                break;
...
        }
    }
```

**Comment by marl0rd** [comment]
@gilbertojrequena : `JetBrains/intellij-community` is actually the whole IDE in open-source?????

**Comment by gilbertojrequena** [comment]
Just the community version

**Comment by gilbertojrequena** [comment]
Implementation finished with https://github.com/eru-scada/eru/commit/4a37b6179675b3b1e3dc645dad5ea3d33792ee28

**Comment by gilbertojrequena** [comment]
Linking components with tags will be covered with another issue.
