### ISSUE TITLE
Tags ID are not setted in the tag creation

### ISSUE THREAD

**Issue by marl0rd** [marlontrujillo1080/eru#51]
To be able to use tags in Displays one have to have the Tag ID. If your workflow is create tags and
immediately after create displays, you have this problem.

**Comment by marl0rd** [comment]
How we can solve this one @gilbertojrequena ???
Any ideas? I can do it but wanted to know your idea... It is something quick but important...

**Comment by gilbertojrequena** [comment]
I don't understand the problem, the tag id is generated when clicking the save button

**Comment by marl0rd** [comment]
That one. There is any way to request the ID in the construction?

**Comment by marl0rd** [comment]
Maybe we need the autosave feature working.

**Comment by marl0rd** [comment]
And on top of that, if you save the tags are not been updated back so you need to restart eru

**Comment by gilbertojrequena** [comment]
Then lets make the save option work properly and then implement the autosave
