### ISSUE TITLE
Where to launch the SCADA?

### ISSUE THREAD

**Issue by marl0rd** [marlontrujillo1080/eru#57]
Currently, the SCADA is been launched by using the manu bar item _Scada > Launch_... This show the Display marked as initial_display. But it seems like it is not the natural workflow...

I have been thinking about putting some button on the Display table row (like the connect on the connection table) to launch the display but I'm not 100% percent sure that is the **right place.**..

What do you think?

**Comment by gilbertojrequena** [comment]
Yes I was thinking the same, adding a button in the display table

**Comment by marl0rd** [comment]
Good. I will do the change...
