### ISSUE TITLE
Main Java package is not OK

### ISSUE THREAD

**Issue by marl0rd** [marlontrujillo1080/eru#59]
Since the organization is called "eru-scada", the main java package have to be **com.eru_scada.eru** for this project, and **com.eru_scada.dynamo** for dynamo project.

So, to follow the [Naming Conventions](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html) we need to make a decision:

1. Create another organization called eruscada, or something else.
2. Change the main java package to eru_scada.
3. Keep using this...

**Comment by Rafaelsk** [comment]
I like to think of the package name as the reversed DNS. If we would have a web page what the DNS could be? www.eruscada.org?
So the package name could be org.eruscada. ...

**Comment by marl0rd** [comment]
Yes, org is a better option. Eruscada sounds funny, maybe we have to find a more generic name as the organization name...

**Comment by marl0rd** [comment]
The SCADA project is called ERU and that's ok.

**Comment by Rafaelsk** [comment]
Ok so eru is the name of the project. Do we also want to have an organization name? That might have other projects later?

**Comment by marl0rd** [comment]
Yes. We have actually three:
- Dynamo
- Device-Simulator
- Eru

**Comment by marl0rd** [comment]
The organization name was changed... Now we need to change the main package name.
